# Generated by Django 5.0.4 on 2024-04-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vaccine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Vaccine Name")),
                ("description", models.TextField(max_length=1024)),
                ("number_of_doses", models.IntegerField(default=1)),
                (
                    "interval",
                    models.IntegerField(default=0, help_text="Interval in days"),
                ),
                ("storage_temperature", models.IntegerField(blank=True, null=True)),
                ("minimum_age", models.IntegerField(default=0)),
            ],
        ),
    ]
